### ISSUE TITLE
When opening a file ran into StackOverflow and Eclipse asking to exit (on Eclipse 4.3.0 only?)

### ISSUE THREAD

**Issue by paulvi** [winterstein/Eclipse-Markdown-Editor-Plugin#33]
When opening a file below ran into StackOverflow and Eclipse asking to exit

https://github.com/felixge/node-mysql/blob/master/Readme.md

(Eclipse failed to start, only renaming project folder (thus making Readme.md unavailable) )

There is definitely circular calls, with no visible class to blame (stack too long).

```
 Unhandled event loop exception
```

eclipse.buildId=4.3.0.I20130605-2000
java.version=1.7.0_40

```
java.lang.StackOverflowError
    at java.util.regex.Pattern$Slice.match(Pattern.java:3867)
    at java.util.regex.Pattern$LazyLoop.match(Pattern.java:4741)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4615)
    at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3715)
    at java.util.regex.Pattern$Curly.match0(Pattern.java:4170)
    at java.util.regex.Pattern$Curly.match(Pattern.java:4132)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4556)
    at java.util.regex.Pattern$LazyLoop.match(Pattern.java:4745)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4615)
    at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3715)
    at java.util.regex.Pattern$Curly.match0(Pattern.java:4170)
    at java.util.regex.Pattern$Curly.match(Pattern.java:4132)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4556)
    at java.util.regex.Pattern$LazyLoop.match(Pattern.java:4745)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4615)
    at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3715)
    at java.util.regex.Pattern$Curly.match0(Pattern.java:4170)
    at java.util.regex.Pattern$Curly.match(Pattern.java:4132)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4556)
    at java.util.regex.Pattern$LazyLoop.match(Pattern.java:4745)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4615)
    at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3715)
    at java.util.regex.Pattern$Curly.match0(Pattern.java:4170)
    at java.util.regex.Pattern$Curly.match(Pattern.java:4132)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4556)
    at java.util.regex.Pattern$LazyLoop.match(Pattern.java:4745)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4615)
    at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3715)
    at java.util.regex.Pattern$Curly.match0(Pattern.java:4177)
    at java.util.regex.Pattern$Curly.match(Pattern.java:4132)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4556)
    at java.util.regex.Pattern$LazyLoop.match(Pattern.java:4745)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4615)
    at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3715)
    at java.util.regex.Pattern$Curly.match0(Pattern.java:4170)
    at java.util.regex.Pattern$Curly.match(Pattern.java:4132)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4556)
    at java.util.regex.Pattern$LazyLoop.match(Pattern.java:4745)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4615)
    at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3715)
    at java.util.regex.Pattern$Curly.match0(Pattern.java:4170)
    at java.util.regex.Pattern$Curly.match(Pattern.java:4132)
    at java.util.regex.Pattern$GroupHead.match(Pattern.java:4556)
    at java.util.regex.Pattern$LazyLoop.match(Pattern.java:4745)
    at java.util.regex.Pattern$GroupTail.match(Pattern.java:4615)
    at java.util.regex.Pattern$BmpCharProperty.match(Pattern.java:3715)
    at java.util.regex.Pattern$Curly.match0(Pattern.java:4170)
    at java.util.regex.Pattern$Curly.match(Pattern.java:4132)
```

 and so on

**Comment by paulvi** [comment]
@eremmel Can you reproduce now as of 2015 with Luna ?

**Comment by paulvi** [comment]
I don't have problem with https://raw.githubusercontent.com/felixge/node-mysql/master/Readme.md on Luna

**Comment by jiangxincode** [comment]
Maybe the file is too large. I guess.
