### ISSUE TITLE
Unhandled Event Loop Exception in Eclipse 3.8 on Ubuntu 14.10.

### ISSUE THREAD

**Issue by nadar** [winterstein/Eclipse-Markdown-Editor-Plugin#54]
When i try to open the **_Preview Window**_ i get the following error:

```
Unhandled event loop exception
No more handles [Unknown Mozilla path (MOZILLA_FIVE_HOME not set)]
```

I am using Eclipse 3.8 on Ubuntu 14.10.

Session Data:

```
eclipse.buildId=debbuild
java.version=1.7.0_65
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Command-line arguments:  -os linux -ws gtk -arch x86_64
```

Exception Stack Trace:

```
org.eclipse.swt.SWTError: No more handles [Unknown Mozilla path (MOZILLA_FIVE_HOME not set)]
    at org.eclipse.swt.SWT.error(SWT.java:4387)
    at org.eclipse.swt.browser.Mozilla.initMozilla(Mozilla.java:1936)
    at org.eclipse.swt.browser.Mozilla.create(Mozilla.java:699)
    at org.eclipse.swt.browser.Browser.<init>(Browser.java:99)
    at winterwell.markdown.views.MarkdownPreview.createPartControl(MarkdownPreview.java:41)
    at org.eclipse.ui.internal.ViewReference.createPartHelper(ViewReference.java:386)
    at org.eclipse.ui.internal.ViewReference.createPart(ViewReference.java:240)
    at org.eclipse.ui.internal.WorkbenchPartReference.getPart(WorkbenchPartReference.java:595)
    at org.eclipse.ui.internal.Perspective.showView(Perspective.java:2245)
    at org.eclipse.ui.internal.WorkbenchPage.busyShowView(WorkbenchPage.java:1145)
    at org.eclipse.ui.internal.WorkbenchPage$20.run(WorkbenchPage.java:3925)
    at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:70)
    at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:3922)
    at org.eclipse.ui.handlers.ShowViewHandler.openView(ShowViewHandler.java:162)
    at org.eclipse.ui.handlers.ShowViewHandler.openOther(ShowViewHandler.java:105)
    at org.eclipse.ui.handlers.ShowViewHandler.execute(ShowViewHandler.java:73)
    at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:290)
    at org.eclipse.core.commands.Command.executeWithChecks(Command.java:499)
    at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:508)
    at org.eclipse.ui.internal.handlers.HandlerService.executeCommand(HandlerService.java:169)
    at org.eclipse.ui.internal.handlers.SlaveHandlerService.executeCommand(SlaveHandlerService.java:241)
    at org.eclipse.ui.internal.ShowViewMenu$3.run(ShowViewMenu.java:187)
    at org.eclipse.jface.action.Action.runWithEvent(Action.java:498)
    at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:584)
    at org.eclipse.jface.action.ActionContributionItem.access$2(ActionContributionItem.java:501)
    at org.eclipse.jface.action.ActionContributionItem$5.handleEvent(ActionContributionItem.java:411)
    at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
    at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1276)
    at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:3562)
    at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3186)
    at org.eclipse.ui.internal.Workbench.runEventLoop(Workbench.java:2701)
    at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2665)
    at org.eclipse.ui.internal.Workbench.access$4(Workbench.java:2499)
    at org.eclipse.ui.internal.Workbench$7.run(Workbench.java:679)
    at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:332)
    at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:668)
    at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:149)
    at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:124)
    at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:110)
    at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:79)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:353)
    at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:180)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:629)
    at org.eclipse.equinox.launcher.Main.basicRun(Main.java:584)
    at org.eclipse.equinox.launcher.Main.run(Main.java:1438)
    at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
```

**Comment by paulvi** [comment]
I guess it is 

> This is a well known problem with xulrunner and eclipse 3.7.

> Here's a workaround.

> https://wiki.archlinux.org/index.php/Eclipse#Autocompletion_and_javadoc_render_crash


https://github.com/winterstein/Eclipse-Markdown-Editor-Plugin/issues/1#issuecomment-11911927

**Comment by nadar** [comment]
Thanks for reply. It seems like the provided #anker in the link is missing on this page. Am i wrong?

**Comment by paulvi** [comment]
Yes, it is actually is.
I am not using Eclipse on Linux so I don''t follow.
I just know that it was Lunix+Eclipse problem as mentioned in #1

Check also in related and similar plugin https://github.com/satyagraha/gfm_viewer/#usage

> The plugin uses Eclipse's default browser, e.g. Internet Explorer on Windows; if you use Ubuntu or other Linux distros, we recommend the WebKit browser; see:

    http://www.eclipse.org/swt/faq.php#browserlinuxrcp
    http://www.eclipse.org/swt/faq.php#browserlinux

Please share what worked for you.

**Comment by paulvi** [comment]
up, how was it?

**Comment by nadar** [comment]
i could not find a solution yet.

**Comment by jiangxincode** [comment]
Maybe the file is too large. I guess.
